name: e_commerce
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter:
    sdk: flutter
  appwrite: ^11.0.1
  google_fonts: ^6.1.0
  get_storage: ^2.1.1
  image_picker: ^1.0.4
  cached_network_image: ^3.3.0
  build_runner: ^2.4.7
  mockito: ^5.4.3
  http: ^1.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_icons: 
  android: true
  image_path: "assets/images/app_logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
